"use client";

import { useEffect, useRef } from "react";
import gsap from "gsap";
import {
  LayoutGrid,
  Users,
  Briefcase,
  Clapperboard,
  Wallet,
  Star,
  Sparkles,
} from "lucide-react";
import {
  eyebrow,
  aiBadgeLabel,
  heroCopy,
  navItems,
  metrics,
  pipelineStage,
  projectRows,
  timing,
  type NavIcon,
} from "./constants";

type Scene04RevealProps = {
  isActive?: boolean;
};

const NAV_ICONS: Record<NavIcon, typeof LayoutGrid> = {
  dashboard: LayoutGrid,
  pipeline: Users,
  projects: Briefcase,
  delivery: Clapperboard,
  accounts: Wallet,
};

// Metrics whose value is plain digits (no currency/comma formatting) count
// up from 0 during construction — a nice "the system is computing this"
// beat that would be fiddly to do safely for the ₹-formatted metrics.
const COUNT_UP_IDS = ["active-leads", "new-week"];

export default function Scene04Reveal({
  isActive = false,
}: Scene04RevealProps) {
  const sceneRef = useRef<HTMLElement | null>(null);
  const hasPlayedRef = useRef(false);

  useEffect(() => {
    if (!sceneRef.current) return;

    const section = sceneRef.current;

    const ctx = gsap.context(() => {
      gsap.set(".ready-line", { opacity: 0 });
      gsap.set(".burst-echo", { opacity: 0 });
      gsap.set(".eyebrow-line", { opacity: 0, y: 10 });
      // The headline "builds" rather than just fades — a scale + blur +
      // opacity reveal reads as materializing out of the burst that caused
      // it. Size/max-width stay within the previously-measured-safe range
      // (see canvas.measureText note in earlier history).
      gsap.set(".headline-line", {
        opacity: 0,
        scale: timing.headlineScaleFrom,
        filter: `blur(${timing.headlineBlurPx}px)`,
        transformOrigin: "center center",
      });
      gsap.set(".subhead-line", { opacity: 0, y: 12 });
      gsap.set(".hero-text", { scale: 1, transformOrigin: "center center" });

      // Workspace assembly. The frame doesn't just fade in in place — it
      // starts tiny and transparent, offset to sit exactly at Scene 3's
      // burst origin (48%/48% of the viewport, the same point its hub
      // converged to), then expands out to its resting size/position in
      // the play effect. So the workspace reads as generated by the hub,
      // not cut to from nowhere. Measured via getBoundingClientRect diff —
      // the same technique used for Scene 3's own object convergence.
      gsap.set(".ambient-glow", { opacity: 0 });
      const frame = section.querySelector(".workspace-frame") as HTMLElement | null;
      let originX = 0;
      let originY = 0;
      if (frame) {
        const rect = frame.getBoundingClientRect();
        originX = window.innerWidth * 0.48 - (rect.left + rect.width / 2);
        originY = window.innerHeight * 0.48 - (rect.top + rect.height / 2);
      }
      gsap.set(".workspace-frame", {
        opacity: 0,
        scale: 0.12,
        x: originX,
        y: originY,
        // The permanent ~2deg rotationX ("floating perspective," like a
        // product photographed at a slight angle) is set once here via
        // GSAP's own rotationX/transformPerspective properties — never a
        // raw CSS transform string — so later scale/position tweens
        // compose on top of it cleanly instead of fighting over the
        // transform property.
        transformPerspective: 1200,
        rotationX: 2,
        transformOrigin: "center center",
      });
      gsap.set(".ai-badge", { opacity: 0, scale: 0.92, y: -4 });
      gsap.set(".sidebar-panel", { opacity: 0, x: -24 });
      gsap.set(".metric-card", { opacity: 0, y: 10, scale: 0.94 });
      gsap.set(".pipeline-col, .projects-col", { opacity: 0, y: 16 });
      // Individual rows get their own tiny entrance on top of their
      // column's — the workspace should read as constructing itself piece
      // by piece, not one block fading in. Tags/status pills get a further
      // beat of their own so they read as a distinct construction step.
      gsap.set(".lead-row, .project-row", { opacity: 0, x: -10 });
      gsap.set(".status-pill, .lead-tag", { opacity: 0 });

      // Count-up metrics start at 0 in the actual DOM (not just visually
      // hidden) so there's no risk of a flash of the real number before
      // the construction count-up tween takes over.
      COUNT_UP_IDS.forEach((id) => {
        const el = section.querySelector(`[data-metric-value="${id}"]`);
        if (el) el.textContent = "0";
      });
    }, section);

    return () => ctx.revert();
  }, []);

  useEffect(() => {
    if (!sceneRef.current) return;
    if (!isActive) return;
    if (hasPlayedRef.current) return;

    hasPlayedRef.current = true;

    const section = sceneRef.current;

    const tl = gsap.timeline();

    // Opens with a residual echo of Scene 3's convergence burst (same
    // position/color as its `.convergence-burst`) instead of a pause —
    // the cut reads as one continuous flash-to-content event, not two
    // separate flashes with a gap between them.
    tl.addLabel("burst");
    tl.fromTo(
      ".burst-echo",
      { opacity: 0.85, scale: 0.4 },
      {
        opacity: 0,
        scale: 2.4,
        duration: timing.burstEchoDuration,
        ease: "power2.out",
        immediateRender: false,
      },
      "burst"
    );

    tl.to(
      ".eyebrow-line",
      { opacity: 1, y: 0, duration: timing.eyebrowDuration, ease: "power2.out" },
      "burst+=0.05"
    );

    tl.addLabel("headline", "burst+=0.18");
    tl.to(
      ".headline-line",
      {
        opacity: 1,
        scale: 1,
        filter: "blur(0px)",
        duration: timing.headlineDuration,
        ease: "power3.out",
        stagger: timing.headlineStagger,
      },
      "headline"
    );
    tl.to(
      ".subhead-line",
      { opacity: 1, y: 0, duration: timing.subheadDuration, ease: "power2.out" },
      "headline+=0.35"
    );

    // Workspace starts before the headline build fully finishes — there's
    // always something visibly in motion, never a blank hold waiting for
    // its turn. The frame itself expands from the hub's burst point first
    // — "the intelligence generating the workspace," not a cut to it —
    // and everything inside it only starts building once that expansion
    // is well underway. UI pieces get a small back.out (a few percent
    // overshoot) rather than a flat power-out — "nothing should snap,"
    // everything settles with a touch of physicality.
    tl.addLabel("workspace", "headline+=0.3");
    tl.to(
      ".ambient-glow",
      { opacity: 1, duration: 0.6, ease: "power1.out" },
      "workspace"
    );
    tl.to(
      ".workspace-frame",
      {
        opacity: 1,
        scale: 1.01,
        x: 0,
        y: 0,
        duration: 0.55,
        ease: "power3.out",
      },
      "workspace"
    );
    tl.to(
      ".sidebar-panel",
      { opacity: 1, x: 0, duration: timing.sidebarDuration, ease: "back.out(1.08)" },
      "workspace+=0.35"
    );
    tl.to(
      ".metric-card",
      {
        opacity: 1,
        y: 0,
        scale: 1,
        duration: timing.metricsDuration,
        ease: "back.out(1.1)",
        stagger: timing.metricsStagger,
      },
      "workspace+=0.55"
    );
    // The two plain-integer metrics count up from 0 as their card pops in
    // — "the system computing this," part of construction, not a static
    // number just appearing.
    tl.call(
      () => {
        COUNT_UP_IDS.forEach((id) => {
          const metric = metrics.find((m) => m.id === id);
          const el = section.querySelector(`[data-metric-value="${id}"]`);
          if (!metric || !el) return;
          const target = parseInt(metric.value, 10);
          const proxy = { val: 0 };
          gsap.to(proxy, {
            val: target,
            duration: 0.5,
            ease: "power2.out",
            onUpdate: () => {
              el.textContent = String(Math.round(proxy.val));
            },
          });
        });
      },
      [],
      "workspace+=0.62"
    );
    tl.to(
      ".pipeline-col",
      { opacity: 1, y: 0, duration: timing.pipelineDuration, ease: "back.out(1.08)" },
      "workspace+=0.72"
    );
    tl.to(
      ".projects-col",
      { opacity: 1, y: 0, duration: timing.projectsDuration, ease: "back.out(1.08)" },
      "workspace+=0.8"
    );
    // Rows assemble on top of their column, each with its own quick
    // stagger — "constructing itself," not fading in as one block. The
    // last lead is held back from this pass — it slides in later, on its
    // own, once the workspace has settled (see the "settled" section
    // below).
    tl.to(
      ".lead-row:not(.lead-row-live)",
      {
        opacity: 1,
        x: 0,
        duration: timing.rowDuration,
        ease: "back.out(1.06)",
        stagger: timing.rowStagger,
      },
      "workspace+=0.9"
    );
    tl.to(
      ".project-row",
      {
        opacity: 1,
        x: 0,
        duration: timing.rowDuration,
        ease: "back.out(1.06)",
        stagger: timing.rowStagger,
      },
      "workspace+=0.98"
    );
    // Status/tag pills land just after their row's text — its own small,
    // distinct construction beat rather than appearing simultaneously with
    // the row.
    tl.to(
      ".status-pill, .lead-tag",
      { opacity: 1, duration: 0.25, ease: "power2.out", stagger: 0.03 },
      "workspace+=1.15"
    );
    tl.to(
      ".ai-badge",
      {
        opacity: 1,
        scale: 1,
        y: 0,
        duration: timing.badgeDuration,
        ease: "power3.out",
      },
      `lock-=${timing.badgeDelay}`
    );

    // Everything locks into place together. The workspace's own expansion
    // (above) already left it a hair oversized (scale 1.01) — this is the
    // tiny overshoot correcting itself, a physical "it just landed" feel
    // rather than a hard stop. The headline block settles at the same
    // time, same duration, so the two halves of the reveal read as one
    // finish.
    tl.addLabel("lock", "workspace+=1.55");
    tl.to(
      ".workspace-frame",
      { scale: 1, duration: timing.lockDuration, ease: "back.out(1.2)" },
      "lock"
    );
    tl.fromTo(
      ".hero-text",
      { scale: 1.012 },
      {
        scale: 1,
        duration: timing.lockDuration,
        ease: "power2.out",
        immediateRender: false,
      },
      "lock"
    );

    tl.to(
      ".ready-line",
      { opacity: 1, duration: timing.readyFadeDuration, ease: "power1.out" },
      "lock+=0.1"
    );

    // Settle finishes, is-live fires (unblocks scroll-lock / marks entrance
    // done) almost immediately after...
    tl.call(
      () => {
        section.classList.add("is-live");
        section.querySelectorAll(".ready-cursor").forEach((el) => {
          el.classList.add("ready-cursor-blink");
        });
      },
      [],
      `lock+=${timing.lockDuration + 0.05}`
    );

    // ...but breathing only begins after a real pause — "settles naturally,
    // then, after a beat, starts breathing" rather than snapping straight
    // into ambient motion.
    tl.addLabel("settled", `lock+=${timing.lockDuration + timing.lockPauseBeforeBreathe}`);
    tl.call(
      () => {
        section.querySelector(".workspace-frame")?.classList.add("breathe-slow");
      },
      [],
      "settled"
    );

    // Living moments — sparse and causal, not simultaneous: a lead arrives,
    // the count reacts to it, a project resolves, the system notices. Only
    // four small beats total, well spaced, so the workspace reads as alive
    // without ever feeling busy.
    tl.to(
      ".lead-row-live",
      { opacity: 1, x: 0, duration: timing.rowDuration, ease: "back.out(1.15)" },
      `settled+=${timing.liveRowDelay}`
    );
    tl.call(
      () => {
        const liveMetric = metrics.find((m) => m.liveValue);
        if (!liveMetric) return;
        const el = section.querySelector(`[data-metric-value="${liveMetric.id}"]`);
        if (!el) return;
        const from = parseInt(liveMetric.value, 10);
        const to = parseInt(liveMetric.liveValue!, 10);
        const proxy = { val: from };
        gsap.to(proxy, {
          val: to,
          duration: 0.6,
          ease: "power2.out",
          onUpdate: () => {
            el.textContent = String(Math.round(proxy.val));
          },
        });
      },
      [],
      `settled+=${timing.liveMetricDelay}`
    );
    tl.to(
      ".ai-badge",
      { scale: 1.08, duration: 0.22, ease: "power2.out", yoyo: true, repeat: 1 },
      `settled+=${timing.liveBadgeDelay}`
    );
  }, [isActive]);

  return (
    <section
      ref={sceneRef}
      className="relative h-screen overflow-hidden bg-[#F7F5F2]"
    >
      <style>{`
        @keyframes readyCursorBlink {
          0%, 40% { opacity: 1; }
          55%, 90% { opacity: 0; }
          100% { opacity: 1; }
        }
        .ready-cursor-blink {
          animation: readyCursorBlink 2.6s ease-in-out infinite;
        }
      `}</style>

      <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,#FFFFFF_0%,#F7F5F2_72%)]" />

      {/* Residual echo of Scene 3's convergence burst — same spot, same
          gold — so the handoff reads as one continuous flash, not a cut
          followed by a blank frame. */}
      <div
        className="burst-echo pointer-events-none absolute h-[220px] w-[220px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#C6A47F]"
        style={{ left: "48%", top: "48%" }}
      />

      <div className="absolute inset-0 flex flex-col items-center px-8 pt-[5.5%] text-center">
        {/* Eyebrow + headline + subhead move as one block — it gets its
            own subtle settle in sync with the workspace's "lock" beat (see
            the .hero-text tween in the play effect) so the two halves of
            the reveal read as one finish. */}
        <div className="hero-text flex flex-col items-center">
          <p className="eyebrow-line text-[16px] font-semibold uppercase tracking-[0.24em] text-[#1D3539] md:text-[17px]">
            {eyebrow}
          </p>

          <h1 className="mt-3 max-w-[820px] font-serif text-[36px] font-medium uppercase leading-[1.18] tracking-[0.01em] text-[#1D3539] md:text-[56px]">
            {heroCopy.headlineLines.map((line) => (
              <span key={line} className="headline-line block whitespace-nowrap">
                {line}
              </span>
            ))}
          </h1>

          <div className="subhead-block mt-11 max-w-[620px] text-[16px] leading-[1.7] text-[#667085] md:text-[18px]">
            {heroCopy.subheadLines.map((line) => (
              <p key={line} className="subhead-line">
                {line}
              </p>
            ))}
          </div>
        </div>

        {/* Workspace — the hero product shot. One continuous surface (real
            HTML, not screenshots), a soft ambient glow behind it, and a
            permanent ~2deg tilt so it reads as photographed, not flat. */}
        <div className="relative mt-9 w-full" style={{ maxWidth: 1320 }}>
          <div
            className="ambient-glow pointer-events-none absolute -inset-10 -z-10 rounded-[50%] bg-[radial-gradient(ellipse_at_center,rgba(198,164,127,0.28),rgba(198,164,127,0)_70%)] blur-3xl"
          />

          <div
            className="workspace-frame relative overflow-hidden rounded-[22px] border border-[#1D3539]/10 bg-white shadow-[0_50px_110px_-24px_rgba(29,53,57,0.26),0_18px_44px_rgba(29,53,57,0.10),inset_0_1px_0_0_rgba(255,255,255,0.9)]"
            style={{ maxWidth: 1320, height: "45vh", minHeight: 360, maxHeight: 520 }}
          >
            <div className="flex h-full">
              <div className="sidebar-panel relative flex w-[84px] shrink-0 flex-col items-center gap-3 border-r border-[#1D3539]/8 bg-[#F7F5F2] py-6">
                {/* Quiet "system is live" cue — barely-there ambient
                    motion, not a feature callout. */}
                <span className="glow-pulse-slow absolute right-3 top-3 h-[5px] w-[5px] rounded-full bg-[#3F6C4E]" />
                {navItems.map((item) => {
                  const Icon = NAV_ICONS[item.icon];
                  return (
                    <div
                      key={item.id}
                      className={`flex h-9 w-9 items-center justify-center rounded-[10px] ${
                        item.active
                          ? "bg-[#C6A47F]/25 text-[#1D3539]"
                          : "text-[#1D3539]/30"
                      }`}
                    >
                      <Icon size={17} strokeWidth={1.75} />
                    </div>
                  );
                })}
              </div>

              <div className="flex flex-1 flex-col gap-5 p-6 text-left">
                <div className="flex items-stretch divide-x divide-[#1D3539]/8">
                  {metrics.map((metric, i) => (
                    <div
                      key={metric.id}
                      className={`metric-card flex-1 ${i === 0 ? "pl-0 pr-5" : "px-5"}`}
                    >
                      <p className="text-[9px] font-medium uppercase tracking-[0.12em] text-[#B48B5A]">
                        {metric.label}
                      </p>
                      <p
                        data-metric-value={metric.id}
                        className={`mt-1.5 font-serif text-[20px] leading-none ${
                          metric.tone === "positive"
                            ? "text-[#3F6C4E]"
                            : "text-[#1D3539]"
                        }`}
                      >
                        {metric.value}
                      </p>
                    </div>
                  ))}
                </div>

                <div className="flex flex-1 divide-x divide-[#1D3539]/8 overflow-hidden">
                  <div className="pipeline-col flex w-[56%] flex-col pr-6">
                    <div className="flex items-center justify-between">
                      <span className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#1D3539]/50">
                        {pipelineStage.name}
                      </span>
                      <span className="text-[10px] text-[#1D3539]/40">
                        {pipelineStage.count} leads
                      </span>
                    </div>
                    <div className="mt-1 flex flex-1 flex-col divide-y divide-[#1D3539]/6 overflow-hidden">
                      {pipelineStage.leads.map((lead) => (
                        <div
                          key={lead.id}
                          className={`lead-row flex items-center gap-2.5 py-2 ${
                            lead.liveAdd ? "lead-row-live" : ""
                          }`}
                        >
                          <Star
                            size={11}
                            strokeWidth={1.75}
                            className="shrink-0 text-[#1D3539]/25"
                          />
                          <span className="flex-1 truncate text-[12.5px] text-[#1D3539]">
                            {lead.name}
                          </span>
                          {lead.tag && (
                            <span className="lead-tag shrink-0 rounded-full bg-[#7B4B2A]/10 px-2 py-0.5 text-[9px] font-medium text-[#7B4B2A]">
                              {lead.tag}
                            </span>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>

                  <div className="projects-col flex flex-1 flex-col pl-6">
                    <span className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#1D3539]/50">
                      PROJECTS
                    </span>
                    <div className="mt-1 flex flex-1 flex-col divide-y divide-[#1D3539]/6 overflow-hidden">
                      {projectRows.map((row) => (
                        <div
                          key={row.id}
                          className="project-row flex items-center justify-between py-2"
                        >
                          <span className="truncate text-[12.5px] text-[#1D3539]">
                            {row.name}
                          </span>
                          <span className="status-pill mx-2 shrink-0 rounded-full bg-[#1D3539] px-2 py-0.5 text-[9px] font-medium text-white">
                            {row.status}
                          </span>
                          <span className="shrink-0 text-[11.5px] font-medium text-[#1D3539]">
                            {row.amount}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* A small tag overlapping the frame's corner, like a spec badge
              on a product shot — not a widget, no controls, just a quiet
              signal that the system is reasoning about the data shown. */}
          <div className="ai-badge pointer-events-none absolute -top-3 right-10 z-10 inline-flex items-center gap-1 rounded-full border border-[#1D3539]/10 bg-white px-2.5 py-1 text-[9px] font-medium uppercase tracking-[0.08em] text-[#1D3539]/70 shadow-[0_6px_18px_rgba(29,53,57,0.14)]">
            <Sparkles size={10} strokeWidth={1.75} className="text-[#C6A47F]" />
            {aiBadgeLabel}
          </div>
        </div>
      </div>

      <p className="ready-line absolute bottom-8 left-1/2 -translate-x-1/2 font-mono text-[13px] text-[#B48B5A]">
        {heroCopy.readyLine} <span className="ready-cursor">▌</span>
      </p>
    </section>
  );
}
